name: CI when PR is Closed to Develop

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build-on-pr-close:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… ì†ŒìŠ¤ì½”ë“œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v3

      - name: â˜• Microsoft OpenJDK 21 ì„¤ì •
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: ğŸ§¹ Gradle ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
        run: chmod +x ./gradlew

      - name: ğŸ›  ë¹Œë“œ
        run: ./gradlew build

      - name: âœ… í…ŒìŠ¤íŠ¸
        run: ./gradlew test
